spring.application.name=email-service

server.port=8086

# RabbitMQ connection details
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nombre de la cola para consumir mensajes
app.rabbitmq.queue.user.registration=user-registration-queue

# Configuracion de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Eureka Health Check
eureka.instance.health-check-url-path=/actuator/health
management.endpoints.web.base-path=/api/email/actuator
eureka.client.healthcheck.enabled=true

# Configuracion de SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=grupo3bootcampaccenture@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000